"""P3.1: ``project_config`` schema, loader and validation.

One JSON file per team describes the project (TVD targets, STV inputs, schedule, agent
settings, file paths). This module defines it as pydantic v2 models, exports the JSON Schema
(``docs/schema/project_config.schema.json``, generated by ``scripts/export_config_schema.py``)
and validates a file beyond types:

- cluster targets sum to the total target within ``tvd.target_sum_tolerance`` (or the
  mismatch is accepted with ``tvd.target_sum_override``)
  (custom clusters: ``carved_out`` counts against the total, ``on_top`` is reported as a
  warning);
- shares/percentages sum to 1.0;
- the STV use phase is complete, or ``not_modeled`` is true;
- dates are in order;
- referenced files exist (warning for optional files);
- no secrets in the file (tokens, URLs with credentials, Discord IDs).

Since P3.2 the TVD and STV engines and the TVD dashboard read their project values from it
(``engines.tvd.targets``, ``engines.stv.project``); the schedule engines follow in P3B.2.

Usage::

    report = validate_config_file("project_config.json")
    if not report.ok:
        print("\\n".join(report.errors))
    config = report.config

    config = load_config("project_config.json")  # raises ConfigError on errors
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import date
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    ValidationError,
    model_validator,
)

SCHEMA_ID = "https://github.com/mxngl/concho/blob/main/docs/schema/project_config.schema.json"
SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"

# Fractions (shares, percentages) must sum to 1.0 within this tolerance.
SHARE_SUM_TOLERANCE = 1e-6

# Differences below this (in currency units) are treated as rounding and not reported.
ROUNDING_AMOUNT = 0.005


# ---------------------------------------------------------------------------
# Enums and small types
# ---------------------------------------------------------------------------


class CourseCluster(StrEnum):
    """TVD clusters A-H as in the course TVD workbook (cluster sheets "A Substructure" ...
    "H Gen. Cond.")."""

    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"
    F = "F"
    G = "G"
    H = "H"


CLUSTER_NAMES: dict[CourseCluster, str] = {
    CourseCluster.A: "Substructure",
    CourseCluster.B: "Shell",
    CourseCluster.C: "Interiors",
    CourseCluster.D: "Services",
    CourseCluster.E: "Equipment and Furnishings",
    CourseCluster.F: "Special Construction",
    CourseCluster.G: "Building Sitework",
    CourseCluster.H: "General Conditions",
}


class CourseTeam(StrEnum):
    """The seven team rows of the course STV workbook (``LCA Data`` rows 115-121)."""

    PACIFIC = "Pacific"
    ATLANTIC = "Atlantic"
    RIDGE = "Ridge"
    ISLAND = "Island"
    RIVER = "River"
    CENTRAL = "Central"
    EXPRESS = "Express"


class Weekday(StrEnum):
    MON = "Mon"
    TUE = "Tue"
    WED = "Wed"
    THU = "Thu"
    FRI = "Fri"
    SAT = "Sat"
    SUN = "Sun"


NonEmptyStr = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
EnvVarName = Annotated[
    str,
    StringConstraints(pattern=r"^[A-Z_][A-Z0-9_]*$"),
    Field(
        description=(
            "Name of an environment variable (UPPER_SNAKE_CASE). The value itself lives in "
            "`.env` / GitHub secrets, never in this file."
        )
    ),
]
Fraction = Annotated[float, Field(ge=0, le=1)]
NonNegative = Annotated[float, Field(ge=0)]
RelPath = Annotated[
    str,
    StringConstraints(strip_whitespace=True, min_length=1),
    Field(description="Path relative to the directory of this config file."),
]


class _Model(BaseModel):
    model_config = ConfigDict(extra="forbid", use_enum_values=False)


def _money(x: float) -> str:
    return f"{x:,.2f}".removesuffix(".00")


# ---------------------------------------------------------------------------
# project
# ---------------------------------------------------------------------------


class ProjectSection(_Model):
    """General project data."""

    name: NonEmptyStr = Field(description="Project name, e.g. the building name.")
    team_name: NonEmptyStr = Field(description="Team name as shown in dashboards and answers.")
    location: NonEmptyStr = Field(description="City, region/country of the site.")
    currency: Annotated[str, StringConstraints(pattern=r"^[A-Z]{3}$")] = Field(
        default="USD", description="ISO 4217 currency code of all amounts in this file."
    )
    units: Literal["imperial"] = Field(
        default="imperial",
        description="Unit system of quantities (only imperial, as in the course workbooks).",
    )
    gross_sf: float = Field(gt=0, description="Gross floor area in square feet ($/SF index).")
    completion_date: date = Field(description="Planned project completion (YYYY-MM-DD).")


# ---------------------------------------------------------------------------
# tvd
# ---------------------------------------------------------------------------


class Budget(_Model):
    """Course budget formula: budget = grant x (1 - inflation + roi) ^ (construction_year -
    grant_year)."""

    grant: float = Field(gt=0, description="Grant amount in the grant year.")
    grant_year: int = Field(ge=1900, le=2200, description="Year the grant is given.")
    construction_year: int = Field(ge=1900, le=2200, description="Year of construction.")
    inflation: Fraction = Field(description="Annual inflation as a fraction (0.03 = 3 %).")
    roi: Fraction = Field(description="Annual return on investment as a fraction.")

    @model_validator(mode="after")
    def _years_in_order(self) -> Budget:
        if self.construction_year < self.grant_year:
            raise ValueError(
                f"construction_year ({self.construction_year}) is before grant_year "
                f"({self.grant_year}); the budget formula needs construction_year >= grant_year."
            )
        return self

    @property
    def amount(self) -> float:
        years = self.construction_year - self.grant_year
        return self.grant * (1 - self.inflation + self.roi) ** years


class ExplicitSplit(_Model):
    """Cluster targets given directly, as shares of the total or as amounts."""

    method: Literal["explicit"]
    basis: Literal["pct", "amount"] = Field(
        description=(
            "`pct`: values are fractions of the course-cluster total (total target minus "
            "carved-out custom clusters) and must sum to 1.0. `amount`: values are currency "
            "amounts that, with the carved-out custom clusters, must sum to the total target."
        )
    )
    values: dict[CourseCluster, NonNegative] = Field(
        description="One value per course cluster A-H (all eight required; 0 is allowed)."
    )

    @model_validator(mode="after")
    def _check_values(self) -> ExplicitSplit:
        missing = [c.value for c in CourseCluster if c not in self.values]
        if missing:
            raise ValueError(
                f"values must list all course clusters A-H; missing: {', '.join(missing)} "
                "(use 0 for a cluster without cost)."
            )
        if self.basis == "pct":
            total = sum(self.values.values())
            if abs(total - 1.0) > SHARE_SUM_TOLERANCE:
                raise ValueError(
                    f"pct values must sum to 1.0, but they sum to {total:.6f}. "
                    "Enter fractions (0.12 = 12 %), not percent numbers."
                )
        return self


class ReferenceColumn(_Model):
    """One reference column of the course "TVD Targets" sheet (RSMeans reference or a
    previous project)."""

    name: NonEmptyStr = Field(description="Column label, e.g. 'RSMeans' or 'Project 1'.")
    shares: dict[CourseCluster, Fraction] = Field(
        description="Share per course cluster A-H; the eight shares must sum to 1.0."
    )

    @model_validator(mode="after")
    def _check_shares(self) -> ReferenceColumn:
        missing = [c.value for c in CourseCluster if c not in self.shares]
        if missing:
            raise ValueError(
                f"reference column '{self.name}' must list all clusters A-H; "
                f"missing: {', '.join(missing)}."
            )
        total = sum(self.shares.values())
        if abs(total - 1.0) > SHARE_SUM_TOLERANCE:
            raise ValueError(
                f"shares of reference column '{self.name}' must sum to 1.0, "
                f"but they sum to {total:.6f}."
            )
        return self


OwnerRating = Annotated[float, Field(ge=0, le=10)]


class ValueItem(_Model):
    """One owner value item of a cluster (course sheet 'TVD Owners', column C), rated 0-10
    by each owner (columns D, E, ...)."""

    item: NonEmptyStr = Field(description="Value item, e.g. 'Energy Efficiency'.")
    ratings: dict[NonEmptyStr, OwnerRating | None] = Field(
        default_factory=dict,
        description=(
            "Rating 0-10 per owner (owner name as in `owners`). A missing owner or null = "
            "blank (ignored, as in the course)."
        ),
    )


class OwnerRatings(_Model):
    """Owner value ratings (course sheet 'TVD Owners'): value items per cluster, each rated
    0-10 by several owners. Cluster value = mean of all ratings of its items."""

    owners: list[NonEmptyStr] = Field(
        min_length=1, description="Owner names (course: 'Owner 1', 'Owner 2')."
    )
    items: dict[CourseCluster, list[ValueItem]] = Field(
        description=(
            "Value items per course cluster A-H (all eight keys required; an empty list = "
            "the cluster is not rated and gets no owner share)."
        )
    )

    @model_validator(mode="after")
    def _check(self) -> OwnerRatings:
        dupes = sorted({o for o in self.owners if self.owners.count(o) > 1})
        if dupes:
            raise ValueError(f"owners must be unique; duplicated: {dupes}.")
        missing = [c.value for c in CourseCluster if c not in self.items]
        if missing:
            raise ValueError(
                f"items must list all clusters A-H; missing: {', '.join(missing)} "
                "(use [] for a cluster without value items)."
            )
        for cluster, items in self.items.items():
            for it in items:
                unknown = sorted(set(it.ratings) - set(self.owners))
                if unknown:
                    raise ValueError(
                        f"items.{cluster.value} '{it.item}': ratings by unknown owner(s) "
                        f"{unknown}; owners are {self.owners}."
                    )
        return self

    def cluster_ratings(self) -> dict[str, list[list[float | None]]]:
        """Per cluster letter: per item the ratings in owner order (None = blank)."""
        return {
            c.value: [[it.ratings.get(o) for o in self.owners] for it in self.items[c]]
            for c in CourseCluster
        }


class DeriveFromReferences(_Model):
    """Course method ('TVD Targets' / 'TVD Owners'): cluster share = mean of the reference
    columns (K), `reallocation_pct` of it reallocated by the owner value ratings
    (L = K x (1 - p) + G x p), plus an optional team adjustment (M); or the target shares
    typed in by the team (column N)."""

    method: Literal["derive_from_references"]
    reference_columns: list[ReferenceColumn] = Field(
        min_length=1,
        max_length=4,
        description=(
            "RSMeans SF estimate and previous projects ('TVD Targets' columns G-J; "
            "course: 1 + 3 columns, up to 4)."
        ),
    )
    owner_ratings: OwnerRatings = Field(
        description="Owner value ratings per value item and owner (course sheet 'TVD Owners')."
    )
    reallocation_pct: Fraction = Field(
        default=0.10,
        description=(
            "Share reallocated by the owner ratings (0.10 = 10 %; 'TVD Owners' C22). "
            "L = K x (1 - reallocation_pct) + G x reallocation_pct."
        ),
    )
    team_adjustment: dict[CourseCluster, Annotated[float, Field(ge=-1, le=1)]] = Field(
        default_factory=dict,
        description=(
            "Additional share per cluster from the team's input ('TVD Targets' column M), "
            "as fractions that sum to 0; missing clusters = 0."
        ),
    )
    target_shares: dict[CourseCluster, Fraction] | None = Field(
        default=None,
        description=(
            "Target share per cluster A-H typed in by the team ('TVD Targets' column N); "
            "must sum to 1.0. null (default) = the target shares are L + M."
        ),
    )

    @model_validator(mode="after")
    def _check(self) -> DeriveFromReferences:
        from engines.tvd.derivation import (  # local: engines.tvd imports this module
            owner_adjusted,
            owner_shares,
            owner_values,
            reference_average,
        )

        values = owner_values(self.owner_ratings.cluster_ratings())
        if self.reallocation_pct > 0 and not any(values.values()):
            raise ValueError(
                "owner_ratings has no rating above 0, so reallocation_pct cannot be "
                "distributed; rate at least one value item or set reallocation_pct to 0."
            )
        adj = sum(self.team_adjustment.values())
        if abs(adj) > SHARE_SUM_TOLERANCE:
            raise ValueError(
                f"team_adjustment must sum to 0 (it moves shares between clusters), but it "
                f"sums to {adj:+.6f}."
            )
        if self.target_shares is not None:
            missing = [c.value for c in CourseCluster if c not in self.target_shares]
            if missing:
                raise ValueError(
                    f"target_shares must list all clusters A-H; missing: {', '.join(missing)}."
                )
            total = sum(self.target_shares.values())
            if abs(total - 1.0) > SHARE_SUM_TOLERANCE:
                raise ValueError(f"target_shares must sum to 1.0, but they sum to {total:.6f}.")
        else:
            refs = [{c.value: col.shares[c] for c in CourseCluster}
                    for col in self.reference_columns]
            owner = owner_adjusted(
                reference_average(refs), owner_shares(values), self.reallocation_pct
            )
            final = {k: v + self.team_adjustment.get(CourseCluster(k), 0.0)
                     for k, v in owner.items()}
            negative = [f"{k} ({v:+.6f})" for k, v in final.items() if v < -SHARE_SUM_TOLERANCE]
            if negative:
                raise ValueError(
                    "team_adjustment makes target shares negative: " + ", ".join(negative) + "."
                )
        return self


ClusterSplit = Annotated[ExplicitSplit | DeriveFromReferences, Field(discriminator="method")]


class CustomCluster(_Model):
    """A team-specific cluster that is not part of the course (flagged non-course data)."""

    name: NonEmptyStr = Field(description="Display name, e.g. 'Equipment Rental'.")
    target: NonNegative = Field(description="Target amount in project currency.")
    mode: Literal["carved_out", "on_top"] = Field(
        description=(
            "`carved_out`: part of the total target (course clusters get the rest). "
            "`on_top`: added on top of the total target (reported as a warning)."
        )
    )
    is_course_data: Literal[False] = Field(
        default=False, description="Always false: custom clusters are team data."
    )


class TVDSection(_Model):
    """Target Value Design: total target, cluster split, custom clusters."""

    total_target: float | None = Field(
        default=None,
        gt=0,
        description="Total target amount. Give this OR `budget` + `target`, not both.",
    )
    budget: Budget | None = Field(
        default=None, description="Course budget formula inputs (requires `target`)."
    )
    target: float | None = Field(
        default=None, gt=0, description="Target set by the team, used together with `budget`."
    )
    cluster_split: ClusterSplit = Field(description="How the total is split into clusters A-H.")
    custom_clusters: list[CustomCluster] = Field(
        default_factory=list, description="Optional non-course clusters."
    )
    target_sum_tolerance: Annotated[float, Field(ge=0, lt=1)] = Field(
        default=0.001,
        description=(
            "Allowed difference between the sum of the cluster targets and the total target, "
            "as a fraction of the total target (0.001 = 0.1 %)."
        ),
    )
    target_sum_override: NonEmptyStr | None = Field(
        default=None,
        description=(
            "Accept cluster targets outside `target_sum_tolerance`: the reason why the "
            "mismatch is intended (e.g. 'targets from an older worksheet, reconciled in "
            "week 6'). null (default) = a mismatch outside the tolerance is an error. The "
            "TVD engine reports the gap with status `override`."
        ),
    )

    @model_validator(mode="after")
    def _check_targets(self) -> TVDSection:
        has_total = self.total_target is not None
        has_budget = self.budget is not None
        if has_total == has_budget:
            raise ValueError(
                "give either total_target (a fixed amount) or budget + target "
                "(course budget formula), not both and not neither."
            )
        if has_budget and self.target is None:
            raise ValueError("budget is set, so target (the team's target amount) is required.")
        if has_total and self.target is not None:
            raise ValueError(
                "target is only used with budget; with total_target, remove target."
            )

        names = [c.name for c in self.custom_clusters]
        reserved = {c.value.lower() for c in CourseCluster} | {
            n.lower() for n in CLUSTER_NAMES.values()
        }
        for name in names:
            if name.lower() in reserved:
                raise ValueError(
                    f"custom cluster '{name}' uses a course cluster letter or name; "
                    "course clusters go into cluster_split."
                )
        dupes = sorted({n for n in names if names.count(n) > 1})
        if dupes:
            raise ValueError(f"custom cluster names must be unique; duplicated: {dupes}.")

        total = self.effective_total
        carved = self.carved_out_total
        if carved > total:
            raise ValueError(
                f"carved-out custom clusters ({_money(carved)}) exceed the total target "
                f"({_money(total)})."
            )
        split = self.cluster_split
        if isinstance(split, ExplicitSplit) and split.basis == "amount":
            course_sum = sum(split.values.values())
            diff = course_sum + carved - total
            if abs(diff) > self.target_sum_tolerance * total and not self.target_sum_override:
                raise ValueError(
                    f"course cluster targets ({_money(course_sum)}) + carved-out custom "
                    f"clusters ({_money(carved)}) = {_money(course_sum + carved)}, which is "
                    f"{_money(abs(diff))} {'above' if diff > 0 else 'below'} the total target "
                    f"{_money(total)} (tolerance {self.target_sum_tolerance:g} = "
                    f"{_money(self.target_sum_tolerance * total)}). Fix the amounts, mark a "
                    "custom cluster as on_top, raise target_sum_tolerance, or accept the "
                    "mismatch with target_sum_override (a reason)."
                )
        return self

    @property
    def effective_total(self) -> float:
        """The total target: `total_target`, or `target` when the budget formula is used."""
        if self.total_target is not None:
            return self.total_target
        assert self.target is not None
        return self.target

    @property
    def carved_out_total(self) -> float:
        return sum(c.target for c in self.custom_clusters if c.mode == "carved_out")

    @property
    def on_top_total(self) -> float:
        return sum(c.target for c in self.custom_clusters if c.mode == "on_top")


# ---------------------------------------------------------------------------
# stv
# ---------------------------------------------------------------------------


class CogenerationSplits(_Model):
    """Shares of the cogeneration fuel per output; must sum to 1.0."""

    electricity: Fraction = Field(description="Share of the fuel used for electricity.")
    heating: Fraction = Field(description="Share of the fuel used for heating.")
    cooling: Fraction = Field(description="Share of the fuel used for cooling.")

    @model_validator(mode="after")
    def _sum_to_one(self) -> CogenerationSplits:
        total = self.electricity + self.heating + self.cooling
        if abs(total - 1.0) > SHARE_SUM_TOLERANCE:
            raise ValueError(
                f"cogeneration splits must sum to 1.0, but they sum to {total:.6f}."
            )
        return self


class Cogeneration(_Model):
    """Cogeneration inputs (course STV workbook, use-phase block). Omit the whole object
    (`null`) when the project has no cogeneration."""

    fuel_type: NonEmptyStr = Field(description="Fuel name as in the course 'Cogen Data' sheet.")
    electricity_kwh: NonNegative = Field(description="Electricity per year (kWh).")
    heating_mj: NonNegative = Field(description="Heating per year (MJ).")
    cooling_kwh: NonNegative = Field(description="Cooling per year (kWh).")
    splits: CogenerationSplits


_WATER_FIELDS = (
    "toilet_gpf",
    "wc_sink_gpm",
    "lab_sink_gpm",
    "kitchen_sink_gpm",
    "shower_gpm",
    "landscaping_gal",
    "rainwater_gal",
)


class WaterUse(_Model):
    """Water fixtures and yearly volumes (course STV workbook, water block)."""

    toilet_gpf: NonNegative | None = Field(default=None, description="Toilet flush (gal/flush).")
    urinal_gpf: NonNegative | None = Field(
        default=None,
        description=(
            "Urinal flush (gal/flush). `null` = no urinals (toilet factor 1.0); an explicit "
            "`0` = course behaviour (the course applies the 0.75 toilet factor whenever the "
            "urinal cell is non-blank). The key must be present unless not_modeled is true. "
            "See docs/decisions.md."
        ),
    )
    wc_sink_gpm: NonNegative | None = Field(default=None, description="WC sink (gal/min).")
    lab_sink_gpm: NonNegative | None = Field(default=None, description="Lab sink (gal/min).")
    kitchen_sink_gpm: NonNegative | None = Field(
        default=None, description="Kitchen sink (gal/min)."
    )
    shower_gpm: NonNegative | None = Field(default=None, description="Shower (gal/min).")
    landscaping_gal: NonNegative | None = Field(
        default=None, description="Landscaping water per year (gal)."
    )
    rainwater_gal: NonNegative | None = Field(
        default=None, description="Rainwater collected per year (gal)."
    )

    def missing(self) -> list[str]:
        out = [f for f in _WATER_FIELDS if getattr(self, f) is None]
        if "urinal_gpf" not in self.model_fields_set:
            out.insert(1, "urinal_gpf")
        return out


class UsePhase(_Model):
    """Operational energy and water per year. Every value is required (0 is allowed but must
    be stated) unless `not_modeled` is true."""

    not_modeled: bool = Field(
        default=False,
        description=(
            "true = the use phase is not modeled; the STV result then covers construction "
            "only (reported as a warning). Requires `not_modeled_reason`."
        ),
    )
    not_modeled_reason: str | None = Field(
        default=None,
        description=(
            "Why the use phase is not modeled (required when `not_modeled` is true), e.g. "
            "'no energy model yet'. Reported in the STV results (`use_phase_status`)."
        ),
    )
    grid_kwh: NonNegative | None = Field(default=None, description="Grid electricity (kWh/yr).")
    onsite_renewable_kwh: NonNegative | None = Field(
        default=None, description="On-site renewable electricity, e.g. PV (kWh/yr)."
    )
    natural_gas_m3: NonNegative | None = Field(
        default=None, description="Natural gas (m3/yr)."
    )
    cogeneration: Cogeneration | None = Field(
        default=None,
        description="Cogeneration inputs; the key must be present (`null` = no cogeneration).",
    )
    water: WaterUse | None = Field(default=None, description="Water fixtures and volumes.")

    @model_validator(mode="after")
    def _complete(self) -> UsePhase:
        if self.not_modeled:
            if not (self.not_modeled_reason or "").strip():
                raise ValueError(
                    "use phase is not modeled but not_modeled_reason is missing: say why "
                    "(e.g. 'no energy model yet'), or state every use-phase value."
                )
            return self
        missing = [
            f for f in ("grid_kwh", "onsite_renewable_kwh", "natural_gas_m3")
            if getattr(self, f) is None
        ]
        if "cogeneration" not in self.model_fields_set:
            missing.append("cogeneration")
        if self.water is None:
            missing.append("water")
        else:
            missing += [f"water.{f}" for f in self.water.missing()]
        if missing:
            raise ValueError(
                f"use phase is incomplete; missing: {', '.join(missing)}. State every value "
                "(0 is allowed; cogeneration: null = none; water.urinal_gpf: null = no "
                "urinals) or set not_modeled: true."
            )
        return self

    def has_values(self) -> bool:
        """True if any value is given (used to warn when not_modeled hides values)."""
        return bool(self.model_fields_set - {"not_modeled", "not_modeled_reason"})

    def all_zero(self) -> bool:
        nums = [self.grid_kwh, self.onsite_renewable_kwh, self.natural_gas_m3]
        if self.water is not None:
            nums += [getattr(self.water, f) for f in _WATER_FIELDS]
            nums.append(self.water.urinal_gpf)
        return self.cogeneration is None and all(not v for v in nums)


class STVConstructionItem(_Model):
    """A construction item that is not in the Revit exports, entered like a row of the course
    sheet 'Construction and Materials' (e.g. PV panels: Energy / 'Photovoltaics (sf)')."""

    assembly: NonEmptyStr = Field(
        description="Course assembly, e.g. 'Energy' ('Construction and Materials' column B)."
    )
    material_type: NonEmptyStr = Field(
        description="Material/Type of the course LCA catalog (or a custom material) for that "
                    "assembly, e.g. 'Photovoltaics (sf)' (column C); checked against the "
                    "catalog when concho-stv runs."
    )
    amount: NonNegative = Field(
        description="Quantity in the unit of material_type (column D), e.g. panel area in sf."
    )
    note: NonEmptyStr = Field(
        description="Where the amount comes from (required), e.g. 'team input, not course "
                    "data: PV area from the team workbook'."
    )


class STVSection(_Model):
    """Sustainable Target Value (life-cycle carbon, energy, water)."""

    course_team: CourseTeam = Field(
        description="Team row of the course STV workbook used for the targets."
    )
    lifetime_years: int = Field(default=50, gt=0, le=200, description="Building lifetime.")
    course_workbook_env: EnvVarName = Field(
        default="COURSE_STV_XLSX",
        description="Env var that holds the local path to the course STV workbook.",
    )
    use_phase: UsePhase
    construction_items: list[STVConstructionItem] = Field(
        default_factory=list,
        description=(
            "Construction items not in the Revit exports (P3.8), e.g. PV panels as "
            "Energy / 'Photovoltaics (sf)', as the course enters them in 'Construction and "
            "Materials'. Added once to the STV project result."
        ),
    )
    custom_materials_file: RelPath | None = Field(
        default=None,
        description=(
            "Optional custom materials CSV (custom_materials.csv format, P3.7). Same as "
            "files.custom_materials; if both are set they must be the same path."
        ),
    )


# ---------------------------------------------------------------------------
# schedule
# ---------------------------------------------------------------------------


class Calendar(_Model):
    """Work calendar."""

    hours_per_day: float = Field(default=8, gt=0, le=24, description="Working hours per day.")
    workdays: list[Weekday] = Field(
        default_factory=lambda: [Weekday.MON, Weekday.TUE, Weekday.WED, Weekday.THU, Weekday.FRI],
        min_length=1,
        description="Working weekdays.",
    )
    holidays: list[date] = Field(default_factory=list, description="Non-working dates.")

    @model_validator(mode="after")
    def _unique(self) -> Calendar:
        if len(set(self.workdays)) != len(self.workdays):
            raise ValueError("workdays contains duplicates.")
        return self


class BlockedWindow(_Model):
    """A period without site work, e.g. hurricane season."""

    name: NonEmptyStr = Field(description="Label, e.g. 'Hurricane season 2030'.")
    start: date = Field(description="First blocked day.")
    end: date = Field(description="Last blocked day.")

    @model_validator(mode="after")
    def _order(self) -> BlockedWindow:
        if self.end < self.start:
            raise ValueError(
                f"blocked window '{self.name}' ends ({self.end}) before it starts ({self.start})."
            )
        return self


class Adapters(_Model):
    """Optional licensed-tool adapters (D8). The core runs with all of them off."""

    alice: bool = Field(default=False, description="ALICE macro schedule import/export.")
    fuzor: bool = Field(default=False, description="Fuzor 4D export.")
    manufacton: bool = Field(default=False, description="Manufacton parts/assemblies/orders.")


DEFAULT_TRADE_SEQUENCE = ["Interior Walls", "MEP", "Ceiling", "Doors", "Interior Finishes"]


class ScheduleSection(_Model):
    """Schedule inputs (P3B.7)."""

    start_date: date = Field(description="Construction start.")
    calendar: Calendar = Field(default_factory=Calendar)
    blocked_windows: list[BlockedWindow] = Field(
        default_factory=list, description="Periods without site work (weather, shutdowns)."
    )
    target_completion: date = Field(description="Target completion of construction.")
    rooms_per_zone: int = Field(default=1, ge=1, description="Takt planner: rooms per zone.")
    trade_sequence: list[NonEmptyStr] = Field(
        default_factory=lambda: list(DEFAULT_TRADE_SEQUENCE),
        min_length=1,
        description="Takt trade order (default = the engine's current fixed sequence).",
    )
    adapters: Adapters = Field(default_factory=Adapters)

    @model_validator(mode="after")
    def _order(self) -> ScheduleSection:
        if self.target_completion <= self.start_date:
            raise ValueError(
                f"target_completion ({self.target_completion}) must be after start_date "
                f"({self.start_date})."
            )
        if len(set(self.trade_sequence)) != len(self.trade_sequence):
            raise ValueError("trade_sequence contains duplicates.")
        return self


# ---------------------------------------------------------------------------
# agent
# ---------------------------------------------------------------------------


class Discord(_Model):
    """Discord IDs are given as env var NAMES only, never as IDs."""

    guild: EnvVarName | None = Field(default=None, description="Env var with the server ID.")
    channels: dict[
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_-]*$")], EnvVarName
    ] = Field(
        default_factory=dict,
        description="Logical channel name (e.g. 'ask', 'debug') -> env var with the channel ID.",
    )


class Extensions(_Model):
    """Optional agent extensions (Phase 10)."""

    transcripts: bool = Field(default=False, description="Meeting transcript agent.")
    clashbot: bool = Field(default=False, description="ClashBot (needs ACC/APS access).")


class AgentSection(_Model):
    """Concho agent settings."""

    default_language: Annotated[str, StringConstraints(pattern=r"^[a-z]{2}(-[A-Z]{2})?$")] = (
        Field(default="en", description="Answer language (ISO 639-1, e.g. 'en', 'de').")
    )
    discord: Discord = Field(default_factory=Discord)
    extensions: Extensions = Field(default_factory=Extensions)


# ---------------------------------------------------------------------------
# files
# ---------------------------------------------------------------------------

REQUIRED_FILES = ("cost_db", "macro_schedule")
OPTIONAL_FILES = ("stv_mapping", "custom_materials", "schedule_rules")


class FilesSection(_Model):
    """Input files and the exports directory, relative to this config file. `cost_db` and
    `macro_schedule` are needed by the engines (error if set but missing, warning if unset);
    the others are optional (warning if set but missing)."""

    cost_db: RelPath | None = Field(
        default=None,
        description="TVD cost DB (cost_db.csv format, P3.4; see docs/engines/tvd.md). The TVD "
                    "engine validates it before the run.",
    )
    stv_mapping: RelPath | None = Field(
        default=None,
        description="STV mapping table (stv_mapping.csv format, P3.6; see docs/engines/stv.md). "
                    "concho-stv maps the Revit exports with it; unset = the default table "
                    "template/stv_mapping.csv.",
    )
    custom_materials: RelPath | None = Field(
        default=None,
        description="STV custom materials (custom_materials.csv format, P3.7; see "
                    "docs/engines/stv.md): EPD-based materials the course catalog lacks, used "
                    "like catalog entries; results that rest on them are flagged.",
    )
    macro_schedule: RelPath | None = Field(
        default=None, description="Macro schedule CSV (P3B.1)."
    )
    schedule_rules: RelPath | None = Field(
        default=None, description="Schedule rules JSON (P3B.2)."
    )
    exports: RelPath = Field(default="exports", description="Directory for Revit exports.")


# ---------------------------------------------------------------------------
# root
# ---------------------------------------------------------------------------


class ProjectConfig(_Model):
    """Concho project configuration (one file per team)."""

    model_config = ConfigDict(
        extra="forbid",
        title="Concho project_config",
        json_schema_extra={"$schema": SCHEMA_DIALECT, "$id": SCHEMA_ID},
    )

    schema_: str | None = Field(
        default=None,
        alias="$schema",
        description="Optional path/URL of the JSON Schema (for editor support).",
    )
    project: ProjectSection
    tvd: TVDSection
    stv: STVSection
    schedule: ScheduleSection
    agent: AgentSection
    files: FilesSection = Field(default_factory=FilesSection)

    @model_validator(mode="after")
    def _cross_section(self) -> ProjectConfig:
        if self.schedule.target_completion > self.project.completion_date:
            raise ValueError(
                f"schedule.target_completion ({self.schedule.target_completion}) is after "
                f"project.completion_date ({self.project.completion_date})."
            )
        a, b = self.stv.custom_materials_file, self.files.custom_materials
        if a and b and Path(a) != Path(b):
            raise ValueError(
                f"stv.custom_materials_file ('{a}') and files.custom_materials ('{b}') differ; "
                "set one of them or use the same path."
            )
        return self


def json_schema() -> dict[str, Any]:
    """The JSON Schema of ``project_config`` (as checked in under docs/schema/)."""
    schema = ProjectConfig.model_json_schema(by_alias=True)
    # Put $schema/$id first for readability.
    head = {k: schema.pop(k) for k in ("$schema", "$id") if k in schema}
    return {**head, **schema}


def json_schema_text() -> str:
    return json.dumps(json_schema(), indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Secret scan (runs on the raw JSON before model validation)
# ---------------------------------------------------------------------------

_SECRET_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("URL with credentials", re.compile(r"[a-z][a-z0-9+.-]*://[^/\s:@]+:[^/\s@]+@", re.I)),
    (
        "URL with a token/key parameter",
        re.compile(
            r"[?&](?:token|access_token|api[_-]?key|apikey|key|secret|password|sig|signature)=",
            re.I,
        ),
    ),
    ("Discord webhook URL", re.compile(r"discord(?:app)?\.com/api/webhooks/", re.I)),
    ("Slack webhook URL", re.compile(r"hooks\.slack\.com/services/", re.I)),
    (
        "webhook URL with UUID",
        re.compile(r"webhook(?:-test)?/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
                   re.I),
    ),
    ("GitHub token", re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_\w{20,})")),
    ("GitHub raw token", re.compile(r"GHSAT[0-9A-Za-z_]")),
    ("API key (sk-...)", re.compile(r"\bsk-[A-Za-z0-9_-]{16,}")),
    ("Slack token", re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}")),
    ("AWS access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("Google API key", re.compile(r"\bAIza[0-9A-Za-z_-]{30,}")),
    ("JSON web token", re.compile(r"\beyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}")),
    ("Discord bot token", re.compile(r"\b[MNO][A-Za-z0-9_-]{23,}\.[A-Za-z0-9_-]{6}\.[\w-]{27,}")),
    ("bearer token", re.compile(r"\bBearer\s+[A-Za-z0-9._~+/=-]{16,}")),
    ("private key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("Discord ID", re.compile(r"^\s*[0-9]{17,20}\s*$")),
]
# A long opaque string with upper, lower and digits and no spaces/dots/slashes.
_OPAQUE = re.compile(r"^[A-Za-z0-9_\-]{32,}$")


def _looks_opaque(value: str) -> bool:
    return bool(
        _OPAQUE.match(value)
        and re.search(r"[a-z]", value)
        and re.search(r"[A-Z]", value)
        and re.search(r"[0-9]", value)
    )


def find_secrets(data: Any, path: str = "") -> list[str]:
    """Return one error message per value that looks like a secret. Values are not echoed."""
    found: list[str] = []
    if isinstance(data, dict):
        for key, value in data.items():
            sub = f"{path}.{key}" if path else str(key)
            found += find_secrets(str(key), sub + " (key)")
            found += find_secrets(value, sub)
    elif isinstance(data, list):
        for i, value in enumerate(data):
            found += find_secrets(value, f"{path}[{i}]")
    elif isinstance(data, bool):
        pass
    elif isinstance(data, int) and 17 <= len(str(abs(data))) <= 20:
        found.append(_secret_msg(path, "Discord ID"))
    elif isinstance(data, str):
        for label, pattern in _SECRET_PATTERNS:
            if pattern.search(data):
                found.append(_secret_msg(path, label))
                break
        else:
            if _looks_opaque(data):
                found.append(_secret_msg(path, "token-like string"))
    return found


def _secret_msg(path: str, label: str) -> str:
    return (
        f"{path or '<root>'}: value looks like a secret ({label}). Secrets and IDs never go "
        "into project_config: put the value into .env / GitHub secrets and reference it by "
        "env var name (e.g. agent.discord.channels.ask = \"DISCORD_CHANNEL_ID_ASK\")."
    )


# ---------------------------------------------------------------------------
# Loader + validation report
# ---------------------------------------------------------------------------


class ConfigError(ValueError):
    """Raised by :func:`load_config` when the config has errors."""

    def __init__(self, errors: list[str]):
        self.errors = errors
        super().__init__("invalid project_config:\n" + "\n".join(f"  - {e}" for e in errors))


@dataclass
class ValidationReport:
    config: ProjectConfig | None = None
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


def _format_loc(loc: tuple[Any, ...]) -> str:
    parts: list[str] = []
    for item in loc:
        if isinstance(item, int):
            parts.append(f"[{item}]")
        else:
            # Discriminated-union tags ('explicit', 'derive_from_references') add noise.
            if item in ("explicit", "derive_from_references") and parts:
                continue
            parts.append(("." if parts else "") + str(item))
    return "".join(parts) or "<root>"


def _format_errors(exc: ValidationError) -> list[str]:
    out = []
    for err in exc.errors(include_url=False):
        msg = err["msg"].removeprefix("Value error, ")
        loc = _format_loc(err["loc"])
        if err["type"] == "missing":
            msg = "required field is missing"
        elif err["type"] == "extra_forbidden":
            msg = "unknown field (check the spelling; see docs/config.md)"
        elif err["type"] == "union_tag_invalid":
            msg = (
                "method must be 'explicit' or 'derive_from_references' "
                f"(got {err.get('input', {}).get('method')!r})"
                if isinstance(err.get("input"), dict)
                else msg
            )
        out.append(f"{loc}: {msg}")
    return out


def _check_files(config: ProjectConfig, base_dir: Path, report: ValidationReport) -> None:
    files = config.files
    for name in REQUIRED_FILES:
        rel = getattr(files, name)
        if rel is None:
            report.warnings.append(
                f"files.{name} is not set; the {'TVD' if name == 'cost_db' else 'schedule'} "
                "engine will need it."
            )
        elif not (base_dir / rel).is_file():
            report.errors.append(
                f"files.{name}: file not found: {rel} (resolved to {base_dir / rel}). "
                "Paths are relative to the config file."
            )
    optional = [(f"files.{n}", getattr(files, n)) for n in OPTIONAL_FILES]
    optional.append(("stv.custom_materials_file", config.stv.custom_materials_file))
    for label, rel in optional:
        if rel is not None and not (base_dir / rel).is_file():
            report.warnings.append(
                f"{label}: optional file not found: {rel} (resolved to {base_dir / rel})."
            )
    exports = base_dir / files.exports
    if exports.exists() and not exports.is_dir():
        report.errors.append(f"files.exports: {files.exports} exists but is not a directory.")


def _collect_warnings(config: ProjectConfig, report: ValidationReport) -> None:
    tvd = config.tvd
    total = tvd.effective_total
    cur = config.project.currency

    if tvd.budget is not None:
        budget = tvd.budget.amount
        if total > budget:
            report.warnings.append(
                f"tvd.target ({_money(total)} {cur}) is above the budget from the course "
                f"formula ({_money(budget)} {cur})."
            )

    split = tvd.cluster_split
    if isinstance(split, DeriveFromReferences) and split.reallocation_pct > 0:
        rated = split.owner_ratings.cluster_ratings()
        unrated = [
            c for c, items in rated.items() if not any(r is not None for i in items for r in i)
        ]
        if unrated:
            report.warnings.append(
                f"tvd.cluster_split.owner_ratings: no owner rating for cluster(s) "
                f"{', '.join(unrated)}; they get no owner share."
            )
    if isinstance(split, ExplicitSplit) and split.basis == "amount":
        course_sum = sum(split.values.values())
        diff = course_sum + tvd.carved_out_total - total
        if abs(diff) > ROUNDING_AMOUNT:
            outside = abs(diff) > tvd.target_sum_tolerance * total
            why = (
                f"outside tolerance {tvd.target_sum_tolerance:g}, accepted by "
                f"target_sum_override: {tvd.target_sum_override}"
                if outside
                else f"within tolerance {tvd.target_sum_tolerance:g}"
            )
            report.warnings.append(
                f"tvd.cluster_split: course clusters + carved-out custom clusters sum to "
                f"{_money(course_sum + tvd.carved_out_total)} {cur}, "
                f"{_money(abs(diff))} {'above' if diff > 0 else 'below'} the total target "
                f"{_money(total)} {cur} ({why})."
            )
        all_sum = course_sum + tvd.carved_out_total + tvd.on_top_total
    else:
        all_sum = total + tvd.on_top_total

    on_top = [c for c in tvd.custom_clusters if c.mode == "on_top"]
    if on_top:
        names = ", ".join(f"{c.name} ({_money(c.target)})" for c in on_top)
        report.warnings.append(
            f"tvd.custom_clusters: on-top cluster(s) {names}: all cluster targets sum to "
            f"{_money(all_sum)} {cur}, {_money(all_sum - total)} {cur} above the total target "
            f"{_money(total)} {cur}. Allowed because mode is on_top; these are not course data."
        )

    up = config.stv.use_phase
    if up.not_modeled:
        report.warnings.append(
            "stv.use_phase.not_modeled is true: the STV project result covers construction "
            f"only, while the target covers construction + {config.stv.lifetime_years} years "
            "of operation."
        )
        if up.has_values():
            report.warnings.append(
                "stv.use_phase: values are given but ignored because not_modeled is true."
            )
    else:
        if up.not_modeled_reason:
            report.warnings.append(
                "stv.use_phase: not_modeled_reason is set but ignored because not_modeled is "
                "false."
            )
        if up.all_zero():
            report.warnings.append(
                "stv.use_phase: all use-phase values are 0. If the use phase is not modeled, "
                "set not_modeled: true with a not_modeled_reason instead."
            )

    sched = config.schedule
    for w in sched.blocked_windows:
        if w.end < sched.start_date or w.start > sched.target_completion:
            report.warnings.append(
                f"schedule.blocked_windows: '{w.name}' ({w.start} to {w.end}) lies outside "
                f"the schedule ({sched.start_date} to {sched.target_completion})."
            )
    for h in sched.calendar.holidays:
        if not sched.start_date <= h <= sched.target_completion:
            report.warnings.append(
                f"schedule.calendar.holidays: {h} lies outside the schedule "
                f"({sched.start_date} to {sched.target_completion})."
            )


def validate_config_data(data: Any, base_dir: Path | str = ".") -> ValidationReport:
    """Validate an already parsed config. File paths resolve against ``base_dir``."""
    report = ValidationReport()
    if not isinstance(data, dict):
        report.errors.append("<root>: the config must be a JSON object.")
        return report
    report.errors += find_secrets(data)
    try:
        config = ProjectConfig.model_validate(data)
    except ValidationError as exc:
        report.errors += _format_errors(exc)
        return report
    _collect_warnings(config, report)
    _check_files(config, Path(base_dir), report)
    if report.ok:
        report.config = config
    return report


def validate_config_file(path: Path | str) -> ValidationReport:
    """Read and validate a ``project_config`` JSON file."""
    path = Path(path)
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return ValidationReport(errors=[f"{path}: cannot read file ({exc.strerror})."])
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        return ValidationReport(
            errors=[f"{path}:{exc.lineno}:{exc.colno}: invalid JSON ({exc.msg})."]
        )
    return validate_config_data(data, base_dir=path.resolve().parent)


def load_config(path: Path | str) -> ProjectConfig:
    """Load a ``project_config`` file; raise :class:`ConfigError` listing all errors."""
    report = validate_config_file(path)
    if not report.ok:
        raise ConfigError(report.errors)
    assert report.config is not None
    return report.config


__all__ = [
    "CLUSTER_NAMES",
    "ConfigError",
    "CourseCluster",
    "CourseTeam",
    "ProjectConfig",
    "ValidationReport",
    "find_secrets",
    "json_schema",
    "json_schema_text",
    "load_config",
    "validate_config_data",
    "validate_config_file",
]

